Stable jkphl/dom-factory support
jkphl/rdfa-lite pull request #9
Opened 2021-06-28 12:04 UTC by blankse

rdfa-lite-microdata only support dom-factory versions < 1 now. Should also support the stable versions 1 of dom-factory

2021-06-28 12:17 UTC, rvanlaak requested changes
Last release is of 2017, so feel free to bump.

Side note; I don't have write access on this repo.

2021-06-28 12:17 UTC, rvanlaak commented on composer.json
> +        "jkphl/dom-factory": "^0.1.2 || ^1"
```suggestion
        "jkphl/dom-factory": "^1"
```

2021-06-28 12:18 UTC, blankse commented
@jkphl Can you make @rvanlaak also maintainer here?

2021-06-28 14:41 UTC, jkphl commented
Done ;)

2021-06-29 08:28 UTC, blankse commented
@rvanlaak So you can release a new Version with this?

2021-06-29 08:50 UTC, merged

2021-06-29 08:51 UTC, rvanlaak commented
tagged [`v0.4.6`](https://github.com/jkphl/rdfa-lite-microdata/releases/tag/v0.4.6)

2021-06-29 08:51 UTC, blankse commented
@rvanlaak Thank you 👍🏼